initFields:
  author: "Abourass (https://github.com/Abourass)"
  description: A really magik lint_golem
  license: MIT
  name: "@magik_io/lint_golem"
  repository: "https://github.com/MagikIO/lint_golem.git"
